name: AI4All
publish_to: none
environment:
  sdk: '>=3.7.0 < 4.0.0'
  flutter: '>=3.27.0'
  
workspace:
  - apps/core
  - apps/plus
  - apps/premium
  - apps/ultimate
  - apps/ultra
  - pkgs/unnu_aux
  - pkgs/unnu_ai_model
  - pkgs/unnu_common
  - pkgs/unnu_ce
  - pkgs/unnu_dxl
  - pkgs/unnu_know
  - pkgs/unnu_mi5
  - pkgs/unnu_ragl
  - pkgs/unnu_sap
  - pkgs/unnu_shared
  - pkgs/unnu_speech
  - pkgs/unnu_tts
  - pkgs/unnu_widgets
  - pkgs/mcp_dart
  - pkgs/serious-python/src/serious_python
  - pkgs/serious-python/src/serious_python_platform_interface
  - pkgs/serious-python/src/serious_python_linux
  - pkgs/serious-python/src/serious_python_darwin
  - pkgs/serious-python/src/serious_python_android
  - pkgs/serious-python/src/serious_python_windows
  - pkgs/unnu_addins_client/unnu_addins_client
  - pkgs/unnu_addins_client/unnu_addins_client_platform_interface
  - pkgs/unnu_addins_client/unnu_addins_client_android
  - pkgs/unnu_addins_client/unnu_addins_client_ios
  - pkgs/unnu_addins_client/unnu_addins_client_windows
  
dev_dependencies:
  melos: ^7.3.0
  
melos:
  repository: https://github.com/sheldonrobinson/AI4All
  categories:
    apps:
      - apps/*
    packages:
      - pkgs/*
  ide:
    intellij:
      enabled: true
  scripts:
    format:package:
      description: "Run `dart format` in a specific package."
      run: melos exec -- dart format .
      packageFilters:
        flutter: true
    analyze:package:
      description: "Run `dart analyze` in a specific package."
      run: melos exec -- dart analyze .
      packageFilters:
        flutter: true
    launcher_icon:
      description: "Update Flutter app's launcher icon in a specific package."
      exec: dart run flutter_launcher_icons:generate
      packageFilters:
        dependsOn: flutter_launcher_icons
    df_asset:
      description: "Generate asset classes from asset directories."
      run: melos exec -- dart run dart_fusion asset
      packageFilters:
        flutter: true
    df_model:
      description: "Update models by generating toJSON, fromJSON and copyWith based on given annotation."
      run: melos exec -- dart run dart_fusion model
      packageFilters:
        flutter: true
    df_localize:
      description: "Generate localization classes from JSON files."
      run: melos exec -- dart run dart_fusion localize
      packageFilters:
        flutter: true
  
  
