name: plus
description: "AI4All Plus Edition"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#  flutter_localizations:
#    sdk: flutter
  unnu_shared: ^0.0.1
  unnu_widgets: ^0.0.1
  unnu_speech: ^0.0.1
  unnu_sap: ^0.0.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.16.9
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  
flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

