name: unnu_widgets
description: "Unnu Widgets package"
version: 0.0.2
homepage: https://konnekted.ai

resolution: workspace

environment:
  sdk: '>=3.7.0 < 4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cross_cache: ^1.1.0
  flutter_chat_ui: ^2.11.1
  flutter_chat_core: ^2.9.0
  flyer_chat_text_message: ^2.6.0
  flyer_chat_system_message: ^2.2.0
  flyer_chat_image_message: ^2.3.0
  flyer_chat_file_message: ^2.4.0
  flyer_chat_text_stream_message: ^2.3.0
  langchain: ^0.8.1
  langchain_core: ^0.4.1
  collection: ^1.19.1
  sembast: ^3.8.5+1
  provider: ^6.1.5
  path: ^1.9.1
  uuid: ^4.5.1
  flutter_link_previewer: ^4.2.0
  readmore_expandable_text: ^0.0.3
  diffutil_dart: ^4.0.1
  unnu_shared:
  flutter_spinkit: ^5.2.2
  asset_cache: ^2.2.0
  async: ^2.13.0
  june: ^1.0.0+1
  quiver: ^3.2.2
  bitmask: ^1.0.1
  markdown: ^7.3.0
  html: ^0.15.6
  hold_to_confirm_button: ^0.0.2
  motion_toast: ^2.14.0
  gpt_markdown: ^1.1.4
  google_nav_bar: ^5.0.7
  share_plus: ^12.0.1
  super_native_extensions: ^0.9.1
  super_clipboard: ^0.9.1
  super_drag_and_drop: ^0.9.1
  flutter_popup_card: ^0.0.6
  feedback: ^3.2.0
  mcp_dart: ^1.0.2
  unnu_ai_model:
  unnu_mi5:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0
  
flutter:
  generate: true # Add this line
  assets:
    - assets/images/user.png
    - assets/images/assistant.png
