name: unnu_speech
description: "Unnu speech package"
version: 0.0.1
homepage: "https://konnekted.ai"

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  stream_transform: ^2.1.1
  collection: ^1.19.1
  siri_wave: ^2.3.0
  animated_text_kit: ^4.2.3
  glow_container: ^1.0.1
  june: ^1.0.0+1
  uuid: ^4.5.1
  unnu_shared:
  unnu_sap:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true # Add this line







