name: unnu_ai_model
description: "Unnu AI Model Manager"
version: 0.0.2
homepage: "https://konnekted.ai"

resolution: workspace

environment:
  sdk: '>=3.7.0 < 4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  langchain:  ^0.8.1
  langchain_core: ^0.4.1
  format: ^1.6.0
  yaml: ^3.1.3
  yaml_writer: ^2.1.0
  yaml_edit: ^2.2.2
  june: ^1.0.0+1
  async: ^2.13.0
  path_provider: ^2.1.5
  path: ^1.9.1
  byte_converter: ^2.2.0
  stream_transform: ^2.1.1
  stream_channel: ^2.1.4
  remove_emoji: ^0.0.10
  uuid: ^4.5.1
  lcpp_ngin: ^1.0.0
  unnu_aux:
  unnu_shared:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

